### ISSUE TITLE
SerialPort settings in configuration file

### ISSUE THREAD

**Issue by marsiliano** [guerinoni/tino#9]
Low level serial settings should be inside the configuration setup. e.g. 115200 8N1
A preferred serial could be added and shown as the default if present e.g. /dev/ttyUSB

**Comment by guerinoni** [comment]
I think this thing is already present in software.

**Comment by marsiliano** [comment]
I have checked it into the configuration file present inside tests/files and there is no fields for those settings. If they are already present please update those files

**Comment by AndreaRicchi** [comment]
Did you check _only-settings.json_ or _only-settings-partial.json_ files inside _tests/files_?
